In [1]:
import torch

1. Create a tensor `a` from `list(range(9))`. Predict and then check the size, offset, and stride.

    1. Create a new tensor using `b = a.view(3, 3)`. What does `view` do? Check that `a` and `b` share the same storage.

    2. Create a tensor `c = b[1:,1:]`. Predict and then check the size, offset, and stride.

2. Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the `torch` library?

    1. Apply the function element-wise to `a`. Why does it return an error?

    2. What operation is required to make the function work?

    3. Is there a version of your function that operates in place?


In [4]:
a = torch.tensor(list(range(9))) # size [9] offset [1] stride [1]
a, a.size(), a.stride()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]), (1,))

In [5]:
b = a.view(3, 3) # Guessing creates a new view of the tensor. Same storage?
id(a.storage()) == id(b.storage())

/var/folders/70/z5v4k8l11vs05yb6dxp5c8m40000gn/T/ipykernel_53036/4062655682.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(a.storage()) == id(b.storage())


True

In [10]:
torch.cos(torch.tensor(0))

tensor(1.)

In [11]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [15]:
a.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [13]:
a.cos_()
a

RuntimeError: result type Float can't be cast to the desired output type Long

In [18]:
a.to(torch.float32).cos_()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [20]:
torch.cos_(a.to(torch.float32))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])